query postPage($input: PostPageInput, $page: Page) {
  postPage(input: $input, page: $page) {
    total
    current
    pageSize
    records {
      id
      title
      published
      updatedAt
      categoryId
      category
      author
    }
  }
}

mutation postAdd($input: PostAddInput!) {
  postAdd(input: $input) {
    id
  }
}
