query postPage($input: PostPageInput, $page: Page) {
  postPage(input: $input, page: $page) {
    total
    current
    pageSize
    records {
      id
      title
      published
      updatedAt
      categoryId
      category
      author
    }
  }
}

query postPublishedPage($input: PostPageInput, $page: Page) {
  postPublishedPage(input: $input, page: $page) {
    total
    pageSize
    current
    records {
      id
      title
      updatedAt
      author
      category
      intro
    }
  }
}

mutation postAdd($input: PostAddInput!) {
  postAdd(input: $input) {
    id
  }
}

query postDetail($input: PostDetailInput!) {
  postDetail(input: $input) {
    id
    title
    content
    categoryId
  }
}

query postPublishedDetail($input: PostPublishedDetailInput!) {
  postPublishedDetail(input: $input) {
    id
    title
    intro
    content
    updatedAt
    categoryId
    author
    category
  }
}

mutation postPublish($input: PostPublishInput!) {
  postPublish(input: $input) {
    message
  }
}

mutation postDelete($input: PostDeleteInput!) {
  postDelete(input: $input) {
    message
  }
}
